
//! Autogenerated weights for `pow_difficulty`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-benchmark-spec.ok6zxD26lV")`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --chain=/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-benchmark-spec.ok6zxD26lV
// --genesis-builder=spec-genesis
// --pallet=pow_difficulty
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=runtime/misc/pow-difficulty/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `pow_difficulty`.
pub trait WeightInfo {
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:0)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::CurrentDifficulty` (r:1 w:1)
	/// Proof: `PowDifficulty::CurrentDifficulty` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::LastAdjustment` (r:0 w:1)
	/// Proof: `PowDifficulty::LastAdjustment` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	fn on_initialize_adjustment() -> Weight;
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:1)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:0 w:1)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:0 w:1)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:0 w:1)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_initialize_activate_params() -> Weight;
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:0)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_initialize_start_window() -> Weight;
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:0)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:1 w:0)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:1 w:0)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_initialize_idle() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:0)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::CurrentDifficulty` (r:1 w:1)
	/// Proof: `PowDifficulty::CurrentDifficulty` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::LastAdjustment` (r:0 w:1)
	/// Proof: `PowDifficulty::LastAdjustment` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	fn on_initialize_adjustment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `240`
		//  Estimated: `1523`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1523))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:1)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:0 w:1)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:0 w:1)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:0 w:1)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_initialize_activate_params() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `247`
		//  Estimated: `1523`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1523))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:0)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_initialize_start_window() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `189`
		//  Estimated: `1523`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1523))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:0)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:1 w:0)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:1 w:0)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_initialize_idle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `240`
		//  Estimated: `1523`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1523))
			.saturating_add(T::DbWeight::get().reads(5))
	}
}

impl WeightInfo for () {
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:0)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::CurrentDifficulty` (r:1 w:1)
	/// Proof: `PowDifficulty::CurrentDifficulty` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::LastAdjustment` (r:0 w:1)
	/// Proof: `PowDifficulty::LastAdjustment` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	fn on_initialize_adjustment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `240`
		//  Estimated: `1523`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1523))
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:1)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:0 w:1)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:0 w:1)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:0 w:1)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_initialize_activate_params() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `247`
		//  Estimated: `1523`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1523))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:0)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:1 w:1)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_initialize_start_window() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `189`
		//  Estimated: `1523`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1523))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	/// Storage: `PowDifficulty::PendingParams` (r:1 w:0)
	/// Proof: `PowDifficulty::PendingParams` (`max_values`: Some(1), `max_size`: Some(38), added: 533, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartBlock` (r:1 w:0)
	/// Proof: `PowDifficulty::WindowStartBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `PowDifficulty::WindowStartMs` (r:1 w:0)
	/// Proof: `PowDifficulty::WindowStartMs` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_initialize_idle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `240`
		//  Estimated: `1523`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1523))
			.saturating_add(RocksDbWeight::get().reads(5))
	}
}
