
//! Autogenerated weights for `resolution_destroy`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-benchmark-spec.ok6zxD26lV")`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --chain=/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-benchmark-spec.ok6zxD26lV
// --genesis-builder=spec-genesis
// --pallet=resolution_destroy
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=/Users/rhett/citizenchain/scripts/benchmark-weight-template.hbs
// --output=runtime/governance/resolution-destroy/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `resolution_destroy`.
pub trait WeightInfo {
	/// Storage: `PublicManage::AccountRegisteredCid` (r:1 w:0)
	/// Proof: `PublicManage::AccountRegisteredCid` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::Institutions` (r:1 w:0)
	/// Proof: `PublicManage::Institutions` (`max_values`: None, `max_size`: Some(645), added: 3120, mode: `MaxEncodedLen`)
	/// Storage: `PrivateManage::AccountRegisteredCid` (r:1 w:0)
	/// Proof: `PrivateManage::AccountRegisteredCid` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `PrivateManage::Institutions` (r:1 w:0)
	/// Proof: `PrivateManage::Institutions` (`max_values`: None, `max_size`: Some(645), added: 3120, mode: `MaxEncodedLen`)
	/// Storage: `PublicAdmins::AdminAccounts` (r:1 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(646480), added: 648955, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionRoles` (r:2 w:0)
	/// Proof: `PublicManage::InstitutionRoles` (`max_values`: None, `max_size`: Some(362), added: 2837, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionRoleAssignments` (r:1 w:0)
	/// Proof: `PublicManage::InstitutionRoleAssignments` (`max_values`: None, `max_size`: Some(539152), added: 541627, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionRolePermissions` (r:3 w:0)
	/// Proof: `PublicManage::InstitutionRolePermissions` (`max_values`: None, `max_size`: Some(35205), added: 37680, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:1 w:1)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:1)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:1)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionGovernanceThresholds` (r:1 w:0)
	/// Proof: `PublicManage::InstitutionGovernanceThresholds` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalVotePlans` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalVotePlans` (`max_values`: None, `max_size`: Some(25829), added: 28304, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalVotesByTicket` (r:1 w:1)
	/// Proof: `InternalVote::InternalVotesByTicket` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalTallies` (r:1 w:1)
	/// Proof: `InternalVote::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCode` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByCode` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCid` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByCid` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalThresholdSnapshot` (r:0 w:1)
	/// Proof: `InternalVote::InternalThresholdSnapshot` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:0 w:1)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn propose_destroy() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `PublicManage::AccountRegisteredCid` (r:1 w:0)
	/// Proof: `PublicManage::AccountRegisteredCid` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::Institutions` (r:1 w:0)
	/// Proof: `PublicManage::Institutions` (`max_values`: None, `max_size`: Some(645), added: 3120, mode: `MaxEncodedLen`)
	/// Storage: `PrivateManage::AccountRegisteredCid` (r:1 w:0)
	/// Proof: `PrivateManage::AccountRegisteredCid` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `PrivateManage::Institutions` (r:1 w:0)
	/// Proof: `PrivateManage::Institutions` (`max_values`: None, `max_size`: Some(645), added: 3120, mode: `MaxEncodedLen`)
	/// Storage: `PublicAdmins::AdminAccounts` (r:1 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(646480), added: 648955, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionRoles` (r:2 w:0)
	/// Proof: `PublicManage::InstitutionRoles` (`max_values`: None, `max_size`: Some(362), added: 2837, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionRoleAssignments` (r:1 w:0)
	/// Proof: `PublicManage::InstitutionRoleAssignments` (`max_values`: None, `max_size`: Some(539152), added: 541627, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionRolePermissions` (r:3 w:0)
	/// Proof: `PublicManage::InstitutionRolePermissions` (`max_values`: None, `max_size`: Some(35205), added: 37680, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:1 w:1)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:1)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:1)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionGovernanceThresholds` (r:1 w:0)
	/// Proof: `PublicManage::InstitutionGovernanceThresholds` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalVotePlans` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalVotePlans` (`max_values`: None, `max_size`: Some(25829), added: 28304, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalVotesByTicket` (r:1 w:1)
	/// Proof: `InternalVote::InternalVotesByTicket` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalTallies` (r:1 w:1)
	/// Proof: `InternalVote::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCode` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByCode` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCid` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByCid` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalThresholdSnapshot` (r:0 w:1)
	/// Proof: `InternalVote::InternalThresholdSnapshot` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:0 w:1)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn propose_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `13106`
		//  Estimated: `649945`
		// Minimum execution time: 222_000_000 picoseconds.
		Weight::from_parts(271_000_000, 0)
			.saturating_add(Weight::from_parts(0, 649945))
			.saturating_add(T::DbWeight::get().reads(26))
			.saturating_add(T::DbWeight::get().writes(23))
	}
}

impl WeightInfo for () {
	/// Storage: `PublicManage::AccountRegisteredCid` (r:1 w:0)
	/// Proof: `PublicManage::AccountRegisteredCid` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::Institutions` (r:1 w:0)
	/// Proof: `PublicManage::Institutions` (`max_values`: None, `max_size`: Some(645), added: 3120, mode: `MaxEncodedLen`)
	/// Storage: `PrivateManage::AccountRegisteredCid` (r:1 w:0)
	/// Proof: `PrivateManage::AccountRegisteredCid` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `PrivateManage::Institutions` (r:1 w:0)
	/// Proof: `PrivateManage::Institutions` (`max_values`: None, `max_size`: Some(645), added: 3120, mode: `MaxEncodedLen`)
	/// Storage: `PublicAdmins::AdminAccounts` (r:1 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(646480), added: 648955, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionRoles` (r:2 w:0)
	/// Proof: `PublicManage::InstitutionRoles` (`max_values`: None, `max_size`: Some(362), added: 2837, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionRoleAssignments` (r:1 w:0)
	/// Proof: `PublicManage::InstitutionRoleAssignments` (`max_values`: None, `max_size`: Some(539152), added: 541627, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionRolePermissions` (r:3 w:0)
	/// Proof: `PublicManage::InstitutionRolePermissions` (`max_values`: None, `max_size`: Some(35205), added: 37680, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:1 w:1)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:1)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:1)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `PublicManage::InstitutionGovernanceThresholds` (r:1 w:0)
	/// Proof: `PublicManage::InstitutionGovernanceThresholds` (`max_values`: None, `max_size`: Some(53), added: 2528, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalVotePlans` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalVotePlans` (`max_values`: None, `max_size`: Some(25829), added: 28304, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalVotesByTicket` (r:1 w:1)
	/// Proof: `InternalVote::InternalVotesByTicket` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalTallies` (r:1 w:1)
	/// Proof: `InternalVote::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCode` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByCode` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCid` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByCid` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalThresholdSnapshot` (r:0 w:1)
	/// Proof: `InternalVote::InternalThresholdSnapshot` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:0 w:1)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn propose_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `13106`
		//  Estimated: `649945`
		// Minimum execution time: 222_000_000 picoseconds.
		Weight::from_parts(271_000_000, 0)
			.saturating_add(Weight::from_parts(0, 649945))
			.saturating_add(RocksDbWeight::get().reads(26))
			.saturating_add(RocksDbWeight::get().writes(23))
	}
}
