
//! Autogenerated weights for `citizen_issuance`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("/tmp/citizenchain-step6.iVEZ1A/fresh-spec.json")`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --chain=/tmp/citizenchain-step6.iVEZ1A/fresh-spec.json
// --genesis-builder=spec-genesis
// --pallet=citizen_issuance
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=scripts/benchmark-weight-template.hbs
// --output=runtime/issuance/citizen-issuance/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `citizen_issuance`.
pub trait WeightInfo {
	/// Storage: `CitizenIssuance::IdentityRewardClaimed` (r:1 w:1)
	/// Proof: `CitizenIssuance::IdentityRewardClaimed` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingIdentityRewardClaimed` (r:1 w:1)
	/// Proof: `CitizenIssuance::PendingIdentityRewardClaimed` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::AccountRewarded` (r:1 w:1)
	/// Proof: `CitizenIssuance::AccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingAccountRewarded` (r:1 w:1)
	/// Proof: `CitizenIssuance::PendingAccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardedCount` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardedCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingRewardCount` (r:1 w:1)
	/// Proof: `CitizenIssuance::PendingRewardCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingRewards` (r:0 w:1)
	/// Proof: `CitizenIssuance::PendingRewards` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn on_voting_identity_registered() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `CitizenIssuance::IdentityRewardClaimed` (r:1 w:1)
	/// Proof: `CitizenIssuance::IdentityRewardClaimed` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingIdentityRewardClaimed` (r:1 w:1)
	/// Proof: `CitizenIssuance::PendingIdentityRewardClaimed` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::AccountRewarded` (r:1 w:1)
	/// Proof: `CitizenIssuance::AccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingAccountRewarded` (r:1 w:1)
	/// Proof: `CitizenIssuance::PendingAccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardedCount` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardedCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingRewardCount` (r:1 w:1)
	/// Proof: `CitizenIssuance::PendingRewardCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingRewards` (r:0 w:1)
	/// Proof: `CitizenIssuance::PendingRewards` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn on_voting_identity_registered() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3593`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(8))
	}
}

impl WeightInfo for () {
	/// Storage: `CitizenIssuance::IdentityRewardClaimed` (r:1 w:1)
	/// Proof: `CitizenIssuance::IdentityRewardClaimed` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingIdentityRewardClaimed` (r:1 w:1)
	/// Proof: `CitizenIssuance::PendingIdentityRewardClaimed` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::AccountRewarded` (r:1 w:1)
	/// Proof: `CitizenIssuance::AccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingAccountRewarded` (r:1 w:1)
	/// Proof: `CitizenIssuance::PendingAccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardedCount` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardedCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingRewardCount` (r:1 w:1)
	/// Proof: `CitizenIssuance::PendingRewardCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::PendingRewards` (r:0 w:1)
	/// Proof: `CitizenIssuance::PendingRewards` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	fn on_voting_identity_registered() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3593`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(8))
	}
}
