
//! Autogenerated weights for `votingengine`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-step9-spec.8IH8QqCB1s")`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --chain=/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-step9-spec.8IH8QqCB1s
// --genesis-builder=spec-genesis
// --pallet=votingengine
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=/Users/rhett/citizenchain/scripts/benchmark-weight-template.hbs
// --output=runtime/votingengine/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `votingengine`.
pub trait WeightInfo {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanupTail` (r:1 w:1)
	/// Proof: `VotingEngine::ScheduledCleanupTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:1 w:0)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::ScheduledCleanups` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CallbackExecutionScopes` (r:0 w:1)
	/// Proof: `VotingEngine::CallbackExecutionScopes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingExecutionRetryExpirations` (r:0 w:1)
	/// Proof: `VotingEngine::PendingExecutionRetryExpirations` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingTerminalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingTerminalCleanups` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn finalize_proposal() -> Weight;
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalVotePlans` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalVotePlans` (`max_values`: None, `max_size`: Some(25829), added: 28304, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn retry_passed_proposal() -> Weight;
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalVotePlans` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalVotePlans` (`max_values`: None, `max_size`: Some(25829), added: 28304, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	fn cancel_passed_proposal() -> Weight;
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:2 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn process_pending_execution() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanupTail` (r:1 w:1)
	/// Proof: `VotingEngine::ScheduledCleanupTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:1 w:0)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::ScheduledCleanups` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CallbackExecutionScopes` (r:0 w:1)
	/// Proof: `VotingEngine::CallbackExecutionScopes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingExecutionRetryExpirations` (r:0 w:1)
	/// Proof: `VotingEngine::PendingExecutionRetryExpirations` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingTerminalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingTerminalCleanups` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn finalize_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `339`
		//  Estimated: `105893`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalVotePlans` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalVotePlans` (`max_values`: None, `max_size`: Some(25829), added: 28304, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn retry_passed_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `617`
		//  Estimated: `105893`
		// Minimum execution time: 26_000_000 picoseconds.
		Weight::from_parts(28_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(T::DbWeight::get().reads(8))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalVotePlans` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalVotePlans` (`max_values`: None, `max_size`: Some(25829), added: 28304, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	fn cancel_passed_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `519`
		//  Estimated: `105893`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(T::DbWeight::get().reads(4))
	}
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:2 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn process_pending_execution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `440`
		//  Estimated: `105893`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(26_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl WeightInfo for () {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanupTail` (r:1 w:1)
	/// Proof: `VotingEngine::ScheduledCleanupTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:1 w:0)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::ScheduledCleanups` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CallbackExecutionScopes` (r:0 w:1)
	/// Proof: `VotingEngine::CallbackExecutionScopes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingExecutionRetryExpirations` (r:0 w:1)
	/// Proof: `VotingEngine::PendingExecutionRetryExpirations` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingTerminalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingTerminalCleanups` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn finalize_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `339`
		//  Estimated: `105893`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(RocksDbWeight::get().reads(9))
			.saturating_add(RocksDbWeight::get().writes(10))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalVotePlans` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalVotePlans` (`max_values`: None, `max_size`: Some(25829), added: 28304, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn retry_passed_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `617`
		//  Estimated: `105893`
		// Minimum execution time: 26_000_000 picoseconds.
		Weight::from_parts(28_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(RocksDbWeight::get().reads(8))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalVotePlans` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalVotePlans` (`max_values`: None, `max_size`: Some(25829), added: 28304, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	fn cancel_passed_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `519`
		//  Estimated: `105893`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(RocksDbWeight::get().reads(4))
	}
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:2 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	fn process_pending_execution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `440`
		//  Estimated: `105893`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(26_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
