
//! Autogenerated weights for `election_vote`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/citizenchain
// benchmark
// pallet
// --runtime=target/release/wbuild/citizenchain/citizenchain.compact.wasm
// --genesis-builder=spec-genesis
// --pallet=election_vote
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=/Users/rhett/citizenchain/scripts/benchmark-weight-template.hbs
// --output=runtime/votingengine/election-vote/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `election_vote`.
pub trait WeightInfo {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::CidByAccountId` (r:1 w:0)
	/// Proof: `CitizenIdentity::CidByAccountId` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::AccountIdByCid` (r:1 w:0)
	/// Proof: `CitizenIdentity::AccountIdByCid` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::PopularElectionVotesByCid` (r:1 w:1)
	/// Proof: `ElectionVote::PopularElectionVotesByCid` (`max_values`: None, `max_size`: Some(203), added: 2678, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_popular_vote(c: u32, ) -> Weight;
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `PublicAdmins::AdminAccounts` (r:1 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(646480), added: 648955, mode: `MaxEncodedLen`)
	/// Storage: `GenesisPallet::Phase` (r:1 w:0)
	/// Proof: `GenesisPallet::Phase` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::MutualElectionVotesByTicket` (r:1 w:1)
	/// Proof: `ElectionVote::MutualElectionVotesByTicket` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_mutual_vote(c: u32, ) -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::CidByAccountId` (r:1 w:0)
	/// Proof: `CitizenIdentity::CidByAccountId` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::AccountIdByCid` (r:1 w:0)
	/// Proof: `CitizenIdentity::AccountIdByCid` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::PopularElectionVotesByCid` (r:1 w:1)
	/// Proof: `ElectionVote::PopularElectionVotesByCid` (`max_values`: None, `max_size`: Some(203), added: 2678, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_popular_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3236 + c * (68 +/-0)`
		//  Estimated: `20131 + c * (2552 +/-0)`
		// Minimum execution time: 56_000_000 picoseconds.
		Weight::from_parts(54_416_968, 0)
			.saturating_add(Weight::from_parts(0, 20131))
			// Standard Error: 3_918
			.saturating_add(Weight::from_parts(1_940_611, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(10))
			.saturating_add(Weight::from_parts(0, 2552).saturating_mul(c.into()))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `PublicAdmins::AdminAccounts` (r:1 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(646480), added: 648955, mode: `MaxEncodedLen`)
	/// Storage: `GenesisPallet::Phase` (r:1 w:0)
	/// Proof: `GenesisPallet::Phase` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::MutualElectionVotesByTicket` (r:1 w:1)
	/// Proof: `ElectionVote::MutualElectionVotesByTicket` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_mutual_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1515 + c * (65 +/-0)`
		//  Estimated: `649945 + c * (2552 +/-0)`
		// Minimum execution time: 53_000_000 picoseconds.
		Weight::from_parts(51_128_696, 0)
			.saturating_add(Weight::from_parts(0, 649945))
			// Standard Error: 4_880
			.saturating_add(Weight::from_parts(1_952_845, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(10))
			.saturating_add(Weight::from_parts(0, 2552).saturating_mul(c.into()))
	}
}

impl WeightInfo for () {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::CidByAccountId` (r:1 w:0)
	/// Proof: `CitizenIdentity::CidByAccountId` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::AccountIdByCid` (r:1 w:0)
	/// Proof: `CitizenIdentity::AccountIdByCid` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::PopularElectionVotesByCid` (r:1 w:1)
	/// Proof: `ElectionVote::PopularElectionVotesByCid` (`max_values`: None, `max_size`: Some(203), added: 2678, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_popular_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3236 + c * (68 +/-0)`
		//  Estimated: `20131 + c * (2552 +/-0)`
		// Minimum execution time: 56_000_000 picoseconds.
		Weight::from_parts(54_416_968, 0)
			.saturating_add(Weight::from_parts(0, 20131))
			// Standard Error: 3_918
			.saturating_add(Weight::from_parts(1_940_611, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(12))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().writes(10))
			.saturating_add(Weight::from_parts(0, 2552).saturating_mul(c.into()))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `PublicAdmins::AdminAccounts` (r:1 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(646480), added: 648955, mode: `MaxEncodedLen`)
	/// Storage: `GenesisPallet::Phase` (r:1 w:0)
	/// Proof: `GenesisPallet::Phase` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::MutualElectionVotesByTicket` (r:1 w:1)
	/// Proof: `ElectionVote::MutualElectionVotesByTicket` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_mutual_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1515 + c * (65 +/-0)`
		//  Estimated: `649945 + c * (2552 +/-0)`
		// Minimum execution time: 53_000_000 picoseconds.
		Weight::from_parts(51_128_696, 0)
			.saturating_add(Weight::from_parts(0, 649945))
			// Standard Error: 4_880
			.saturating_add(Weight::from_parts(1_952_845, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(11))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().writes(10))
			.saturating_add(Weight::from_parts(0, 2552).saturating_mul(c.into()))
	}
}
