
//! Autogenerated weights for `provincialbank_interest`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-benchmark-spec.ok6zxD26lV")`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --chain=/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-benchmark-spec.ok6zxD26lV
// --genesis-builder=spec-genesis
// --pallet=provincialbank_interest
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=runtime/issuance/provincialbank-interest/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `provincialbank_interest`.
pub trait WeightInfo {
	/// Storage: `ProvincialBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ProvincialBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ProvincialBankInterest::TotalProvincialBankInterestIssued` (r:1 w:1)
	/// Proof: `ProvincialBankInterest::TotalProvincialBankInterestIssued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ProvincialBankInterest::LastProvincialBankInterestAudit` (r:0 w:1)
	/// Proof: `ProvincialBankInterest::LastProvincialBankInterestAudit` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	fn on_finalize_settlement() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ProvincialBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ProvincialBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ProvincialBankInterest::TotalProvincialBankInterestIssued` (r:1 w:1)
	/// Proof: `ProvincialBankInterest::TotalProvincialBankInterestIssued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ProvincialBankInterest::LastProvincialBankInterestAudit` (r:0 w:1)
	/// Proof: `ProvincialBankInterest::LastProvincialBankInterestAudit` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	fn on_finalize_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1619`
		//  Estimated: `112919`
		// Minimum execution time: 568_000_000 picoseconds.
		Weight::from_parts(572_000_000, 0)
			.saturating_add(Weight::from_parts(0, 112919))
			.saturating_add(T::DbWeight::get().reads(45))
			.saturating_add(T::DbWeight::get().writes(46))
	}
}

impl WeightInfo for () {
	/// Storage: `ProvincialBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ProvincialBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ProvincialBankInterest::TotalProvincialBankInterestIssued` (r:1 w:1)
	/// Proof: `ProvincialBankInterest::TotalProvincialBankInterestIssued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ProvincialBankInterest::LastProvincialBankInterestAudit` (r:0 w:1)
	/// Proof: `ProvincialBankInterest::LastProvincialBankInterestAudit` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	fn on_finalize_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1619`
		//  Estimated: `112919`
		// Minimum execution time: 568_000_000 picoseconds.
		Weight::from_parts(572_000_000, 0)
			.saturating_add(Weight::from_parts(0, 112919))
			.saturating_add(RocksDbWeight::get().reads(45))
			.saturating_add(RocksDbWeight::get().writes(46))
	}
}
