
//! Autogenerated weights for `internal_vote`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-benchmark-spec.ok6zxD26lV")`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --chain=/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-benchmark-spec.ok6zxD26lV
// --genesis-builder=spec-genesis
// --pallet=internal_vote
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=runtime/votingengine/internal-vote/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `internal_vote`.
pub trait WeightInfo {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalVotesByTicket` (r:1 w:1)
	/// Proof: `InternalVote::InternalVotesByTicket` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalTallies` (r:1 w:1)
	/// Proof: `InternalVote::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalThresholdSnapshot` (r:1 w:0)
	/// Proof: `InternalVote::InternalThresholdSnapshot` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn cast() -> Weight;
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanupTail` (r:1 w:1)
	/// Proof: `VotingEngine::ScheduledCleanupTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:1 w:0)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::ScheduledCleanups` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CallbackExecutionScopes` (r:0 w:1)
	/// Proof: `VotingEngine::CallbackExecutionScopes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingExecutionRetryExpirations` (r:0 w:1)
	/// Proof: `VotingEngine::PendingExecutionRetryExpirations` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingTerminalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingTerminalCleanups` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn finalize_internal_timeout() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalVotesByTicket` (r:1 w:1)
	/// Proof: `InternalVote::InternalVotesByTicket` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalTallies` (r:1 w:1)
	/// Proof: `InternalVote::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalThresholdSnapshot` (r:1 w:0)
	/// Proof: `InternalVote::InternalThresholdSnapshot` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn cast() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `423`
		//  Estimated: `67255`
		// Minimum execution time: 32_000_000 picoseconds.
		Weight::from_parts(34_000_000, 0)
			.saturating_add(Weight::from_parts(0, 67255))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanupTail` (r:1 w:1)
	/// Proof: `VotingEngine::ScheduledCleanupTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:1 w:0)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::ScheduledCleanups` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CallbackExecutionScopes` (r:0 w:1)
	/// Proof: `VotingEngine::CallbackExecutionScopes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingExecutionRetryExpirations` (r:0 w:1)
	/// Proof: `VotingEngine::PendingExecutionRetryExpirations` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingTerminalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingTerminalCleanups` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn finalize_internal_timeout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `344`
		//  Estimated: `105893`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(33_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(10))
	}
}

impl WeightInfo for () {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalVotesByTicket` (r:1 w:1)
	/// Proof: `InternalVote::InternalVotesByTicket` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalTallies` (r:1 w:1)
	/// Proof: `InternalVote::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalThresholdSnapshot` (r:1 w:0)
	/// Proof: `InternalVote::InternalThresholdSnapshot` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn cast() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `423`
		//  Estimated: `67255`
		// Minimum execution time: 32_000_000 picoseconds.
		Weight::from_parts(34_000_000, 0)
			.saturating_add(Weight::from_parts(0, 67255))
			.saturating_add(RocksDbWeight::get().reads(8))
			.saturating_add(RocksDbWeight::get().writes(8))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SafetyFundProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SafetyFundProposalActions` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
	/// Storage: `MultisigTransfer::SweepProposalActions` (r:1 w:0)
	/// Proof: `MultisigTransfer::SweepProposalActions` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanupTail` (r:1 w:1)
	/// Proof: `VotingEngine::ScheduledCleanupTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:1 w:0)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::ScheduledCleanups` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CallbackExecutionScopes` (r:0 w:1)
	/// Proof: `VotingEngine::CallbackExecutionScopes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingExecutionRetryExpirations` (r:0 w:1)
	/// Proof: `VotingEngine::PendingExecutionRetryExpirations` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingTerminalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingTerminalCleanups` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn finalize_internal_timeout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `344`
		//  Estimated: `105893`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(33_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(RocksDbWeight::get().reads(9))
			.saturating_add(RocksDbWeight::get().writes(10))
	}
}
