import { invoke } from '../../tauri';
import type { VoteSignRequestResult, VoteSubmitResult } from './types';

// 多签转账模块专用 Tauri API，对齐后端 src/transaction/multisig_transfer。
export const multisigTransferApi = {
  buildMultisigTransferRequest: (
    signer_public_key: string,
    actorCidNumber: string,
    proposerRoleCode: string,
    institution_account_id: string,
    beneficiary_ss58_address: string,
    amountYuan: number,
    remark: string,
  ) =>
    invoke<VoteSignRequestResult>('build_multisig_transfer_request', {
      signer_public_key,
      actor_cid_number: actorCidNumber,
      proposer_role_code: proposerRoleCode,
      institution_account_id,
      beneficiary_ss58_address,
      amount_yuan: amountYuan,
      remark,
    }),
  submitMultisigTransfer: (
    requestId: string,
    expected_signer_public_key: string,
    expectedPayloadHash: string,
    actorCidNumber: string,
    proposerRoleCode: string,
    institution_account_id: string,
    beneficiary_ss58_address: string,
    amountYuan: number,
    remark: string,
    signNonce: number,
    signBlockNumber: number,
    responseJson: string,
  ) =>
    invoke<VoteSubmitResult>('submit_multisig_transfer', {
      request_id: requestId,
      expected_signer_public_key,
      expected_payload_hash: expectedPayloadHash,
      actor_cid_number: actorCidNumber,
      proposer_role_code: proposerRoleCode,
      institution_account_id,
      beneficiary_ss58_address,
      amount_yuan: amountYuan,
      remark,
      sign_nonce: signNonce,
      sign_block_number: signBlockNumber,
      response_json: responseJson,
    }),
  buildProposeSweepRequest: (
    signer_public_key: string,
    actorCidNumber: string,
    proposerRoleCode: string,
    institution_account_id: string,
    amountYuan: number,
  ) =>
    invoke<VoteSignRequestResult>('build_multisig_sweep_request', {
      signer_public_key,
      actor_cid_number: actorCidNumber,
      proposer_role_code: proposerRoleCode,
      institution_account_id,
      amount_yuan: amountYuan,
    }),
  submitProposeSweep: (
    requestId: string,
    expected_signer_public_key: string,
    expectedPayloadHash: string,
    actorCidNumber: string,
    proposerRoleCode: string,
    institution_account_id: string,
    amountYuan: number,
    signNonce: number,
    signBlockNumber: number,
    responseJson: string,
  ) =>
    invoke<VoteSubmitResult>('submit_multisig_sweep', {
      request_id: requestId,
      expected_signer_public_key,
      expected_payload_hash: expectedPayloadHash,
      actor_cid_number: actorCidNumber,
      proposer_role_code: proposerRoleCode,
      institution_account_id,
      amount_yuan: amountYuan,
      sign_nonce: signNonce,
      sign_block_number: signBlockNumber,
      response_json: responseJson,
    }),
  buildProposeSafetyFundRequest: (
    signer_public_key: string,
    actorCidNumber: string,
    proposerRoleCode: string,
    institution_account_id: string,
    beneficiary_ss58_address: string,
    amountYuan: number,
    remark: string,
  ) =>
    invoke<VoteSignRequestResult>('build_multisig_safety_fund_request', {
      signer_public_key,
      actor_cid_number: actorCidNumber,
      proposer_role_code: proposerRoleCode,
      institution_account_id,
      beneficiary_ss58_address,
      amount_yuan: amountYuan,
      remark,
    }),
  submitProposeSafetyFund: (
    requestId: string,
    expected_signer_public_key: string,
    expectedPayloadHash: string,
    actorCidNumber: string,
    proposerRoleCode: string,
    institution_account_id: string,
    beneficiary_ss58_address: string,
    amountYuan: number,
    remark: string,
    signNonce: number,
    signBlockNumber: number,
    responseJson: string,
  ) =>
    invoke<VoteSubmitResult>('submit_multisig_safety_fund', {
      request_id: requestId,
      expected_signer_public_key,
      expected_payload_hash: expectedPayloadHash,
      actor_cid_number: actorCidNumber,
      proposer_role_code: proposerRoleCode,
      institution_account_id,
      beneficiary_ss58_address,
      amount_yuan: amountYuan,
      remark,
      sign_nonce: signNonce,
      sign_block_number: signBlockNumber,
      response_json: responseJson,
    }),
};
